### ISSUE TITLE
Dataset Inquiry

### ISSUE THREAD

**Issue by AryakRoy** [HamidrezaZarrabi/BlessMark#1]
Where did you find the Angiography Dataset and if possible can you please share the link for the hosted dataset (e.g Kaggle).

**Comment by HamidrezaZarrabi** [comment]
> 
Hi. It is not my datadet and I have taken the dataset from [paper](https://www.sciencedirect.com/science/article/abs/pii/S1746809417302215)

**Comment by HamidrezaZarrabi** [comment]
> Where did you find the Angiography Dataset and if possible can you please share the link for the hosted dataset (e.g Kaggle).
Hi. It is not my datadet and I have taken the dataset from [paper](https://www.sciencedirect.com/science/article/abs/pii/S1746809417302215)

**Comment by HamidrezaZarrabi** [comment]
> Where did you find the Angiography Dataset and if possible can you please share the link for the hosted dataset (e.g Kaggle).

Hi. It is not my datadet and I have taken the dataset from [paper](https://www.sciencedirect.com/science/article/abs/pii/S1746809417302215)
